// export const buttonVariants2 = [
//   {
//     variant: "tonal" as "tonal",
//     size: "lg",
//     loading: true,
//     rounded: true,
//     iconPosition: "left" as "left",
//   },
// ];
export const buttonVariants = [
  // Variants-focused buttons
  {
    variant: "default" as "default",
    size: "md",
    iconPosition: "left" as "left",
  },
  {
    variant: "outlined" as "outlined",
    size: "md",
    iconPosition: "left" as "left",
  },
  {
    variant: "plain" as "plain",
    size: "md",
    iconPosition: "left" as "left",
  },
  {
    variant: "primary" as "primary",
    size: "md",
    color: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "text" as "text",
    size: "md",
    iconPosition: "left" as "left",
  },
  {
    variant: "tonal" as "tonal",
    size: "md",
    color: true,
    iconPosition: "left" as "left",
  },

  {
    variant: "outlined" as "outlined",
    size: "lg",
    color: true,
    block: true,
    icon: true,
    iconPosition: "right" as "right",
  },
  {
    variant: "primary" as "primary",
    size: "sm",
    rounded: true,

    icon: true,
    iconPosition: "top" as "top",
  },
  {
    variant: "tonal" as "tonal",
    size: "md",
    only: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "text" as "text",
    size: "lg",
    color: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "plain" as "plain",
    size: "sm",
    disabled: true,
    iconPosition: "right" as "right",
  },
  {
    variant: "default" as "default",
    size: "sm",
    color: true,
    block: true,
    loading: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "outlined" as "outlined",
    size: "md",
    rounded: true,
    only: true,
    icon: true,
    iconPosition: "top" as "top",
  },
  {
    variant: "tonal" as "tonal",
    size: "lg",
    disabled: true,
    icon: true,
    iconPosition: "right" as "right",
  },
  {
    variant: "text" as "text",
    size: "md",
    color: true,
    block: true,
    rounded: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "primary" as "primary",
    size: "md",
    icon: true,
    only: true,
    iconPosition: "left" as "left",
  },
  // Props-focused buttons (Set 1)
  {
    variant: "default" as "default",
    size: "md",
    color: true,
    block: true,
    rounded: true,
    icon: true,
    iconPosition: "right" as "right",
  },
  {
    variant: "default" as "default",
    size: "lg",
    disabled: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "default" as "default",
    size: "sm",
    color: true,
    rounded: true,
    loading: true,
    icon: true,
    iconPosition: "top" as "top",
  },
  {
    variant: "default" as "default",
    size: "md",
    block: true,
    rounded: true,
    only: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "default" as "default",
    size: "md",
    color: true,
    icon: true,
    iconPosition: "right" as "right",
  },
  {
    variant: "default" as "default",
    size: "lg",
    color: true,
    block: true,
    rounded: true,
    iconPosition: "left" as "left",
  },

  // More prop combinations (Set 2)
  {
    variant: "outlined" as "outlined",
    size: "lg",
    disabled: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "plain" as "plain",
    size: "sm",
    color: true,
    icon: true,
    iconPosition: "top" as "top",
  },
  {
    variant: "text" as "text",
    size: "md",
    color: true,
    icon: true,
    iconPosition: "right" as "right",
  },
  {
    variant: "tonal" as "tonal",
    size: "lg",
    block: true,
    rounded: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "primary" as "primary",
    size: "md",
    rounded: true,
    only: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "outlined" as "outlined",
    size: "md",
    loading: true,
    color: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "default" as "default",
    size: "lg",
    icon: true,
    rounded: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "plain" as "plain",
    size: "md",
    color: true,
    icon: true,
    disabled: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "tonal" as "tonal",
    size: "lg",
    rounded: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "text" as "text",
    size: "lg",
    block: true,
    loading: true,
    icon: true,
    iconPosition: "top" as "top",
  },

  // ✨ New Additions: Even More prop combinations (Set 3) ✨
  {
    variant: "text" as "text",
    size: "sm",
    disabled: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "text" as "text",
    size: "md",
    loading: true,
    rounded: true,
    color: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "plain" as "plain",
    size: "lg",
    block: true,
    rounded: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "plain" as "plain",
    size: "sm",
    only: true,
    icon: true,
    color: true,
    rounded: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "outlined" as "outlined",
    size: "lg",
    icon: true,
    iconPosition: "left" as "left",
    color: true,
  },
  {
    variant: "outlined" as "outlined",
    size: "md",
    only: true,
    rounded: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "tonal" as "tonal",
    size: "md",
    disabled: true,
    icon: true,
    color: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "primary" as "primary",
    size: "sm",
    icon: true,
    iconPosition: "top" as "top",
  },
  {
    variant: "primary" as "primary",
    size: "lg",
    disabled: true,
    block: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "default" as "default",
    size: "md",
    disabled: true,
    icon: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "tonal" as "tonal",
    size: "lg",
    only: true,
    icon: true,
    loading: true,
    rounded: true,
    iconPosition: "left" as "left",
  },
  {
    variant: "default" as "default",
    size: "md",
    block: true,
    icon: true,
    iconPosition: "left" as "left",
    color: true,
    rounded: true,
  },
];
